### ISSUE TITLE
Multiple sensors of same type

### ISSUE THREAD

**Issue by Kimotu** [afarago/esphome_component_bthome#3]
I have a device with two batteries. One solar charged to power the ESP, one with standard batteries for relais. So I want to monitor both batteries.

<html><body>

Object id | Property | Data type | Factor | Example | Result | Unit
-- | -- | -- | -- | -- | -- | --
0x01 | battery | uint8 (1 byte) | 1 | 0161 | 97 | %

</body>
</html>

But since the match is done just by object type and there is no other id, I cannot create two sensors with the same property and object type. Dave W used in [his ESP-NOW implementation](https://gitlab.com/dbuggz/ripnetuk-esphome-easynow) ids to match values. Unfortunatelly its ESP32 only - not ESP8266 usable.

```
beethowen_transmitter:
  id: bh_transmitter
  connect_persistent: true
  local_passkey: ${local_pass}
  sensors:
    - measurement_type: battery
      sensor_id: battery1
    - measurement_type: battery
      sensor_id: battery2
sensor:
# ...
   - platform: copy
      source_id: vcc1
      name: "Battery Level µP"
      unit_of_measurement: '%'
      device_class: battery
      id: battery1
      filters:
        - lambda: return (((x - 2.7)/ 1.5) * 100.00);
        - lambda: if (x < 0) return 0.0; else if (x > 100) return 100.0; else return (x);

  - platform: copy
     source_id: vcc2
     name: "Battery Level Relais"
     unit_of_measurement: '%'
     device_class: battery
     id: battery2
       filters:
         - lambda: return (((x - 5.0)/ 1.11) * 100.00);
         - lambda: if (x < 0) return 0.0; else if (x > 100) return 100.0; else return (x);
```

Does BTHome not allow multiple sensors of same type?

**Comment by afarago** [comment]
[bthome specification](https://bthome.io/format) allows multiple sensors of the same type, however at that point order or sensors plays an important role.

It is possible to use two sensors of same type within beethowen.
Please check it, I have tried and it works for me.

If you'd face issues after trying, please add both yaml files and a log using minimum debug log level.

**Comment by Kimotu** [comment]
Ok, I think this is something that needs to be mentioned in documentation. But this means that always all sensor values are transmitted - else it would not be clear which one is the current transmitted one.
