### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by konistehrad** [afarago/esphome_component_bthome#9]
Hello! I'm currently working on making a [BTHomev2 broadcasting component](https://github.com/esphome/feature-requests/issues/1862) for ESPHome, and your `bthome_base` component looks like an excellent starting point. Unfortunately, I don't see a license attached to the project or the source files. Would it be possible to get some clarification on the code licensure? Just want to make sure I'm coloring in the lines.

Thanks again for this awesome lib!

**Comment by afarago** [comment]
Hello, awesome and happy to see you working on that.
Added a generic MIT license, feel free to experiment and attribute.

---
I have plans to extract the BTHome v2 to a separate Arduino library and provide it as a dependency, yet failed to follow up on the steps.

This would have the advantage
* bthome encoder/decoder library available from Arduino
* bthome library would be linked by the esphome component

Once I do this I will update the project dependency as well.

I will add new types to the bthome encoder/decoder as they emerge (e.g. 0x53).
